# Generated by Django 3.2 on 2021-04-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сourse', models.CharField(max_length=200, null=True)),
                ('group_name', models.CharField(max_length=200, null=True)),
                ('year_admission', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocsCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ПРОТОКОЛ', 'ПРОТОКОЛ'), ('ПОЛОЖЕНИЕ', 'ПОЛОЖЕНИЕ'), ('ПРЕЗЕНТАЦИЯ', 'ПРЕЗЕНТАЦИЯ'), ('ДОКУМЕНТ', 'ДОКУМЕНТ')], max_length=200, null=True)),
                ('cource', models.CharField(choices=[('ПКС', 'ПКС'), ('ОИБАС', 'ОИБАС'), ('ИСИП', 'ИСИП')], max_length=200, null=True)),
                ('year', models.CharField(choices=[('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('4 курс', '4 курс')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocsCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ПРОТОКОЛ', 'ПРОТОКОЛ'), ('ПОЛОЖЕНИЕ', 'ПОЛОЖЕНИЕ'), ('ПРЕЗЕНТАЦИЯ', 'ПРЕЗЕНТАЦИЯ'), ('ДОКУМЕНТ', 'ДОКУМЕНТ')], max_length=200, null=True)),
                ('direction', models.CharField(choices=[('ОБЩЕЕ', 'ОБЩЕЕ'), ('КУЛЬТМАСС', 'КУЛЬТМАСС'), ('СПОРТ', 'СПОРТ'), ('ПРОФКА', 'ПРОФКА'), ('ИНФОРМ', 'ИНФОРМ'), ('МУЛЬТИМЕДИА', 'МУЛЬТИМЕДИА')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('login', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('main_text', models.CharField(max_length=200, null=True)),
                ('common_text', models.CharField(max_length=200, null=True)),
                ('tags', models.ManyToManyField(to='accounts.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('score', models.CharField(max_length=200, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
