# Generated by Django 3.2 on 2021-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210429_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docscouncil',
            name='direction',
            field=models.CharField(choices=[('ОБЩЕЕ', 'ОБЩЕЕ'), ('КУЛЬТМАСС', 'КУЛЬТМАСС'), ('СПОРТ', 'СПОРТ'), ('ПРОФКА', 'ПРОФКА'), ('ИНФОРМ', 'ИНФОРМ'), ('МУЛЬТИМЕДИА', 'МУЛЬТИМЕДИА'), ('КЛУБЫ', 'КЛУБЫ')], max_length=200, null=True),
        ),
    ]
