# Generated by Django 3.2 on 2021-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_docscouncil_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='group_name',
            new_name='group_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='year_admission',
        ),
        migrations.RemoveField(
            model_name='docscollege',
            name='year',
        ),
        migrations.AddField(
            model_name='company',
            name='specialty',
            field=models.CharField(choices=[('ПКС', 'ПКС'), ('ОИБАС', 'ОИБАС'), ('ИСИП', 'ИСИП')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='docscollege',
            name='specialty',
            field=models.CharField(choices=[('ПКС', 'ПКС'), ('ОИБАС', 'ОИБАС'), ('ИСИП', 'ИСИП')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='сourse',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docscollege',
            name='cource',
            field=models.CharField(choices=[('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('4 курс', '4 курс')], max_length=200, null=True),
        ),
    ]
