# Generated by Django 3.2 on 2021-04-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210430_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunction',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
