# Generated by Django 3.2 on 2021-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userfunction_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(max_length=200, null=True)),
                ('main_text', models.CharField(max_length=200, null=True)),
                ('common_text', models.CharField(max_length=200, null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
