# Generated by Django 3.2 on 2021-04-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
