# Generated by Django 3.2 on 2021-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_about_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_performance', models.DateField(null=True)),
                ('tags', models.ManyToManyField(to='accounts.Tag')),
            ],
        ),
    ]
