# Generated by Django 3.2 on 2021-04-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
