# Generated by Django 3.2 on 2021-05-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210503_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.event'),
        ),
        migrations.AddField(
            model_name='new',
            name='members',
            field=models.ManyToManyField(to='accounts.Member'),
        ),
    ]
