# Generated by Django 3.2 on 2021-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210503_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Member'),
        ),
    ]
