# Generated by Django 3.2 on 2021-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_new_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='common_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='main_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
