# Generated by Django 3.2 on 2021-05-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210503_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='members',
        ),
    ]
