# Generated by Django 3.2 on 2021-05-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_student_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='score',
        ),
    ]
