# Generated by Django 3.2 on 2021-05-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210508_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docscouncil',
            name='tag',
        ),
        migrations.AddField(
            model_name='docscouncil',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tag'),
        ),
        migrations.AlterField(
            model_name='new',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.event'),
        ),
        migrations.AlterField(
            model_name='new',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
