# Generated by Django 3.2 on 2021-05-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210509_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraward',
            name='award',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
