# Generated by Django 3.2 on 2021-05-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_useraward_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraward',
            name='award',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
