# Generated by Django 3.2 on 2021-05-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_useraward_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraward',
            name='date_performance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
