# Generated by Django 3.2 on 2021-05-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_useraward_date_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
