# Generated by Django 3.2 on 2021-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210510_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, default='rec.png', null=True, upload_to=''),
        ),
    ]
