# Generated by Django 3.2 on 2021-05-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_new_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='photo',
        ),
    ]
