# Generated by Django 3.2 on 2021-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, default='rec.png', null=True, upload_to=''),
        ),
    ]
