# Generated by Django 3.2 on 2021-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='third_text',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='common_text',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='main_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
