# Generated by Django 3.2 on 2021-05-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_listdirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdirection',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
