# Generated by Django 3.2 on 2021-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_listdirection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vk_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
