# Generated by Django 3.2 on 2021-05-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210512_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
