# Generated by Django 3.2 on 2021-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_student_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfunction',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userfunction',
            name='user',
        ),
        migrations.AddField(
            model_name='docscollege',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='docscouncil',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
        migrations.DeleteModel(
            name='UserFunction',
        ),
    ]
