# Generated by Django 3.2 on 2021-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_remove_useraward_date_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docscollege',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docscouncil',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DocsName',
        ),
    ]
