# Generated by Django 3.2 on 2021-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210520_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
