# Generated by Django 3.2 on 2021-05-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_useraward_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraward',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
    ]
