# Generated by Django 3.2 on 2021-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_useraward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='docscollege',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='docscouncil',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
