# Generated by Django 3.2 on 2021-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20210525_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='main_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
