# Generated by Django 3.2 on 2021-05-26 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_new_main_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
    ]
