# Generated by Django 3.2 on 2021-06-01 13:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20210527_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='about',
            name='result',
        ),
        migrations.RemoveField(
            model_name='more',
            name='goals',
        ),
        migrations.AddField(
            model_name='about',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='more',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='more',
            name='main_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='more',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
